services:
  cuatrimestreapp:
    image: cuatrimestreapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://cuatrimestreapp-mssql:1433;database=CuatrimestreApp;encrypt=false
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://cuatrimestreapp-mssql:1433;database=CuatrimestreApp;encrypt=false
    ports:
      - 8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      cuatrimestreapp-mssql:
        condition: service_healthy
  cuatrimestreapp-mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_DATABASE=CuatrimestreApp
      - MSSQL_SLEEP=15
    command: /bin/bash -c '/opt/mssql/bin/sqlservr & echo "wait $$MSSQL_SLEEP sec for DB to start "; sleep $$MSSQL_SLEEP; /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -d tempdb -q "EXIT(CREATE DATABASE $$MSSQL_DATABASE)"; wait;'
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -Q "USE $${MSSQL_DATABASE}" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
