spring:
  datasource:
    url: jdbc:sqlserver://HOST:1433;databaseName=CuatrimestreApp;encrypt=true;trustServerCertificate=true
    username: SA
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: false

  mail:
    host: ""
    port: 0
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

server:
  port: 8080

jhipster:
  mail:
    from: noreply@localhost
    base-url: http://localhost

  security:
    authentication:
      jwt:
        base64-secret: YmFiZGJmMjg3NDZiMjVkODJlNzU1MDAyZDMzNmQyNmMyZDk4NTYxODFkMWJhZmZiNjZkZjYwODVkNjE5OTE5MDI5OTg4YTM1OTNmYTlkNzdjOThlNWQ3MGY2NDE1MzVmY2Q0MjkwZjA1MWRmNzg0NjgyY2NiYTYwZDRiNmMwNGY=
